APP_APIID = 838650
APP_APIHASH = '03df7cdaf00d8c27b4c0f4f94d4bef24'

USER_PHONENUMBER = 'phoneNumber'
USER_USERNAME = 'username'

CHAT_SOURCE_CHAT_IDS = 'sourceChatIds'
CHAT_DESTINATION_CHAT_IDS = 'destinationChatIds'

ENV_ENVIRONMENT_FUNCTION = 'environmentFunction'

ENV_FUNCTION_READ_AND_FOREWARD = 'read_and_foreward'
ENV_FUNCTION_ALTER_AND_FOREWARD = 'alter_and_foreward'

ORDER_TYPE = 'TYPE'
ORDER_INSATRUMENT = 'INSTR'
ORDER_PRICE = 'PRICE'
ORDER_STOP_LOSS = 'SL'
ORDER_TAKE_PROFIT = 'TP'
ORDER_STATUS = 'STATUS'